const mainCategories = {
    "İzin & Çalışma Saatleri": ["İzin Talebi", "İzin Bakiyesi Sorgulama", "Uzaktan Çalışma"],
    "Maaş & Ödemeler": ["Maaş Sorunları", "Bordro & Vergi Belgeleri", "Masraf Geri Ödeme"],
    "İK & Yan Haklar": ["Sağlık Sigortası", "Emeklilik Planları", "Çalışan Avantajları"],
    "BT & Teknik Destek": ["Şifre Sıfırlama", "Teknik Sorunlar", "BT Ekipman Talebi"],
    "Ofis & Çalışma Ortamı": ["Toplantı Odası Rezervasyonu", "Ofis Alanı Kullanımı"],
    "Eğitim & Gelişim": ["Mesleki Kurslar", "Sertifika Programları", "Yetkinlik Geliştirme"],
    "İşe Alım & Referans": ["Çalışan Referansları", "İş Başvuruları"],
    "Performans & Geri Bildirim": ["Performans Değerlendirme", "Çalışan Geri Bildirimi"],
    "Şirket Politikaları": ["Çalışma Kuralları", "Güvenlik Politikaları"],
    "İşten Ayrılma": ["İstifa Süreci", "Çıkış İşlemleri"],
};

var subcategory = {
    "İzin Talebi": ["İzin talebini nasıl oluşturabilirim?"],
    "İzin Bakiyesi Sorgulama": ["Kalan izin günlerimi nereden kontrol edebilirim?"],
    "Uzaktan Çalışma": ["Uzaktan çalışma politikası nedir?"],
    "Maaş Sorunları": ["Maaşım ile ilgili bir sorun yaşarsam ne yapmalıyım?"],
    "Bordro & Vergi Belgeleri": ["Bordromu ve vergi belgelerimi nereden alabilirim?"],
    "Masraf Geri Ödeme": ["Masraf geri ödemesi için nasıl başvurabilirim?"],
    "Sağlık Sigortası": ["Şirketin sağlık sigortası avantajları nelerdir?"],
    "Emeklilik Planları": ["Emeklilik planları hakkında nasıl bilgi alabilirim?"],
    "Çalışan Avantajları": ["Şirketin sunduğu avantajları ve indirimleri nereden öğrenebilirim?"],
    "Şifre Sıfırlama": ["Şirket hesabımın şifresini nasıl sıfırlayabilirim?"],
    "Teknik Sorunlar": ["Teknik bir sorun yaşarsam ne yapmalıyım?"],
    "BT Ekipman Talebi": ["Uzaktan çalışma için BT ekipmanı talep edebilir miyim?"],
    "Toplantı Odası Rezervasyonu": ["Toplantı odası nasıl rezerve edilir?"],
    "Ofis Alanı Kullanımı": ["Ofiste çalışma alanı rezervasyonu nasıl yapılır?"],
    "Mesleki Kurslar": ["Eğitim veya mesleki gelişim kurslarına nasıl başvurabilirim?"],
    "Sertifika Programları": ["Sertifika programlarına nasıl katılabilirim?"],
    "Yetkinlik Geliştirme": ["Yetkinlik geliştirme eğitimlerine nasıl erişebilirim?"],
    "Çalışan Referansları": ["Bir arkadaşımı açık pozisyonlar için nasıl önerebilirim?"],
    "İş Başvuruları": ["Şirkette açık pozisyonları nereden görebilirim?"],
    "Performans Değerlendirme": ["Performans değerlendirmemi nereden görebilirim?"],
    "Çalışan Geri Bildirimi": ["Geri bildirim süreci nasıl işler?"],
    "Çalışma Kuralları": ["Şirket çalışma kurallarına nereden ulaşabilirim?"],
    "Güvenlik Politikaları": ["Şirketin güvenlik politikaları hakkında nasıl bilgi alabilirim?"],
    "İstifa Süreci": ["İşten ayrılma süreci nasıl işler?"],
    "Çıkış İşlemleri": ["İşten ayrıldıktan sonra hangi işlemleri tamamlamalıyım?"],
};
